# Generated by Django 3.0.3 on 2020-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201109_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nonce',
            field=models.IntegerField(default=1518974),
        ),
    ]
