# Generated by Django 3.0.3 on 2020-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20201009_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('product_id', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('common_name', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('product_id', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('common_name', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('product_id', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('common_name', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholesalerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('product_id', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('common_name', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
