# Generated by Django 3.0.3 on 2020-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20201107_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='common_name',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
    ]
