# Generated by Django 3.0.3 on 2020-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20201107_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='common_name',
            field=models.TextField(blank=True, max_length=105, null=True),
        ),
    ]
