# Generated by Django 3.0.3 on 2020-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20201107_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='executor',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expiry_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('tons', 'tons'), ('bags', 'bags'), ('pieces', 'pieces')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
